version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[Fix]'
    ignore:
      - dependency-name: 'next'
        versions: ['<15.2.0']
