import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from './util/ReactQuery/ReactQuery';
import Footer from '@/components/common/Footer';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Footer />
      </body>
    </html>
  );
}
